version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '8511:81'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "dbcustom"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "nginxuser"
      DB_MYSQL_PASSWORD: "custompwd"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - dbcustom
  dbcustom:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpwd'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'nginxuser'
      MYSQL_PASSWORD: 'custompwd'
    volumes:
      - ./data/mysql:/var/lib/mysql
