 
 Vagrant.configure("2") do |config|

  config.vm.box = "clickonrefresh/clickonrefresh-ubuntu20.04"
  
  # Network settings
  config.vm.network "private_network",
   
  # Provider-specific configuration 
  config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
  vb.memory = "1024"
  vb.cpus = 1
  end
  
  config.vm.provision "shell", path: "adminapps.sh"
     
end
