name: crispy-waffles
base: core20
version: "0.1"
summary: Web Application Suite
description: A highly customizable suite of web applications, to do pretty much anything with.
grade: devel
confinement: strict

apps:
  crispy-waffles:
    command: vagrant up
    
parts:
  crispy-waffles:
    source: https://github.com/Crispy-Waffles/Crispy-Waffles/archive/refs/tags/0.0.1.tar.gz
    plugin: autotools
