# Set some variables to use globally
BOX_IMAGE = "clickonrefresh/clickonrefresh-ubuntu20.04"

Vagrant.configure("2") do |config|
    config.vm.define "master" do |i|
        i.vm.boot_timeout = 600
        i.vm.box = BOX_IMAGE
        i.vm.hostname = "admin"
        i.vm.network "public_network"#, ip: "192.168.100.50"
        # Provider-specific configuration
        i.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = 1
          vb.name = "admin"
        end
        i.vm.provision "shell", path: "adminapps.sh"
    end
  
    config.vm.define "main" do |i|
        i.vm.boot_timeout = 600
        i.vm.box = BOX_IMAGE
        i.vm.hostname = "main"
        i.vm.network "private_network"#, ip: "192.168.52.51"
        # Provider-specific configuration
        i.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
            vb.name = "main"
        end
            i.vm.provision "shell", path: "mainapps.sh"
    end

      
    config.vm.define "alt" do |i|
        i.vm.boot_timeout = 600
        i.vm.box = BOX_IMAGE
        i.vm.hostname = "alt"
        i.vm.network "private_network"#, ip: "192.168.52.52"
        # Provider-specific configuration
        i.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 1
            vb.name = "alt"
        end
        i.vm.provision "shell", path: "altapps.sh"
end
end
