# Set some variables to use globally
BOX_IMAGE = "clickonrefresh/clickonrefresh-ubuntu20.04"
NODE_COUNT = 3
var_ssh_user = "clickonrefresh"
var_ssh_keypath = "~/.ssh/id_rsa"

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "clickonadmin"
    subconfig.vm.network "private_network"
    subconfig.vm.network "public_network", ip: "192.168.1.40"
    subconfig.ssh.private_key_path = var_ssh_keypath
    subconfig.ssh.username = var_ssh_user
    subconfig.ssh.verify_host_key = :always
    # Provider-specific configuration 
    subconfig.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.name = clickonadmin
    subconfig.vm.provision "shell", path: "adminapps.sh"
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "clickonmain"
      subconfig.vm.network "private_network"
      subconfig.ssh.private_key_path = var_ssh_keypath
      subconfig.ssh.username = var_ssh_user
      subconfig.ssh.verify_host_key = :always
      # Provider-specific configuration 
      subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = clickonmain
      subconfig.vm.provision "shell", path: "mainapps.sh"
    end
      
      (2..NODE_COUNT).each do |ii|
        config.vm.define "node#{ii}" do |subconfig|
          subconfig.vm.box = BOX_IMAGE
          subconfig.vm.hostname = "clickonalt"
          subconfig.vm.network "private_network"
          subconfig.ssh.private_key_path = var_ssh_keypath
          subconfig.ssh.username = var_ssh_user
          subconfig.ssh.verify_host_key = :always
          # Provider-specific configuration 
          subconfig.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = 1
          vb.name = clickonalt
          subconfig.vm.provision "shell", path: "altapps.sh"
        end
  end
end
