# Set some variables to use globally
BOX_IMAGE = "clickonrefresh/clickonrefresh-ubuntu20.04"
NODE_COUNT = 3


Vagrant.configure("2") do |config|
  config.vm.define "master" do |i|
    i.vm.box = BOX_IMAGE
    i.vm.hostname = "clickonadmin"
    i.vm.network "public_network", ip: "192.168.1.40"
    i.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "clickonadmin"
    i.vm.provision "shell", path: "adminapps.sh"
    end
  end
  
  (1..NODE_COUNT).each do |ii|
    config.vm.define "clickonmain" do |ii|
      ii.vm.box = BOX_IMAGE
      ii.vm.hostname = "clickonmain"
      ii.vm.network "public_network", ip: "192.168.1.41"
      ii.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
        vb.name = "clickonmain"
      ii.vm.provision "shell", path: "mainapps.sh"
      end
    end
    
      
    (2..NODE_COUNT).each do |iii|
      config.vm.define "clickonalt" do |iii|
        iii.vm.box = BOX_IMAGE
        iii.vm.hostname = "clickonalt"
        iii.vm.network "public_network", ip: "192.168.1.42"
        iii.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = 1
          vb.name = "clickonalt"
        iii.vm.provision "shell", path: "altapps.sh"
        end
      end
    end
  end
end
